# Copyright 2024 Robo Coder Jet
# 

name: 'Build Totem'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left","totem_right","settings_reset"]'
      nav: '["invertedt"]'
      clipboard: '["win"]'
      layers: '["flip"]'
