# Copyright 2024 Robo Coder Jet
# 

name: 'Build Sweep'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["cradio_left","cradio_right"]'
      nav: '["invertedt"]'
      clipboard: '["win"]'
      layers: '["flip"]'